"""cascade delete for messages and citations

Revision ID: 098176bebbfe
Revises: 6b5c3cd41bc3
Create Date: 2026-07-16 16:44:54.415882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098176bebbfe'
down_revision: Union[str, Sequence[str], None] = '6b5c3cd41bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('citations_message_id_fkey'), 'citations', type_='foreignkey')
    op.create_foreign_key(None, 'citations', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'citations', type_='foreignkey')
    op.create_foreign_key(op.f('citations_message_id_fkey'), 'citations', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###
