"""add model and token usage columns to messages

Revision ID: 25bce72eaada
Revises: 098176bebbfe
Create Date: 2026-07-17 11:57:32.344973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bce72eaada'
down_revision: Union[str, Sequence[str], None] = '098176bebbfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('model', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('total_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'total_tokens')
    op.drop_column('messages', 'output_tokens')
    op.drop_column('messages', 'input_tokens')
    op.drop_column('messages', 'model')
    # ### end Alembic commands ###
