name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'uc1-RAG-Knowledge-Chatbot/frontend/**'
      - '.github/workflows/azure-static-web-apps-agreeable-dune-0d56d760f.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    defaults:
      run:
        working-directory: ./uc1-RAG-Knowledge-Chatbot/frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_API_BASE: https://rag-bs-backend.azurewebsites.net
          VITE_APP_API_KEY: ${{ secrets.VITE_APP_API_KEY }}
        run: npm run build

      - name: Install OIDC Client from Core Package
        working-directory: .
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_DUNE_0D56D760F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./uc1-RAG-Knowledge-Chatbot/frontend/dist"
          output_location: ""
          skip_app_build: true
          github_id_token: ${{ steps.idtoken.outputs.result }}
